baseURL = "https://cshugo.mansoorbarri.com"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Coming Soon Hugo" 
    description = "A simple countdown"
    message = "COMING SOON!" # default is "COMING SOON" 
    release = "Jan 30, 2024" # release date format: Aug 30, 2023 15:00
    background = "" # default is bg.mp4 in static/

socialIcons = [
    {name = "email", url = "example@example.com"},      
    {name = "twitter", url = "https://twitter.com/"},    
    {name = "facebook", url = "https://facebook.com/"},    
    {name = "github", url = "https://github.com/"},    
    {name = "instagram", url = "https://instagram.com/"},    
    {name = "tiktok", url = "https://tiktok.com/"},    
] 
