baseURL = "https://cshugo.mansoorbarri.com"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Coming Soon Hugo" 
    description = "A simple countdown"
    favicon = ""
    message = "COMING SOON!" 
    release = "January 1, 2026"
    background = "" 

socialIcons = [
    {name = "email", url = "example@example.com"},      
    {name = "twitter", url = "https://twitter.com/"},    
    {name = "facebook", url = "https://facebook.com/"},    
    {name = "github", url = "https://github.com/"},    
    {name = "instagram", url = "https://instagram.com/"},    
    {name = "tiktok", url = "https://tiktok.com/"},    
    {name = "linkedin", url = "https://linkedin.com/"},    
] 

[params.twitter]
	enable = false 
	username = "mansoorbarri"
